public enum Phase {
  PARSED,
  INDEXED,
  SUPERING, SUPERED,
  MEMBERING, MEMBERED,
  PREPARING, PREPARED,
  VERIFYING, VERIFIED,
  RECURSING, RECURSED,
  SOLVING, SOLVED,
  EMITTING, EMITTED,
  FINISHED
}
